require 'rails_helper'

RSpec.describe InvoiceItem, type: :model do
  it { is_expected.to belong_to(:item) }
  it { is_expected.to belong_to(:invoice) }

  describe 'Instance Methods' do
    describe '.revenue' do
      it "returns revenue generated by the invoice item" do
        inv_item =  create(:invoice_item, quantity: 12, unit_price: 6)
        expect(inv_item.revenue).to eq(72)
      end
    end
  end
end
